// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'


    show defaultTargetPlatform, kIsWeb, TargetPlatform;
// import 'firebase_options.dart';
//
// // ...
//
// await Firebase.initializeApp(
// options: DefaultFirebaseOptions.currentPlatform,
// );
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeMq3LOjOKcgrlOMG6PxxVXVps31YFkiM',
    appId: '1:285154808193:web:bedc123fee0f372ecb5880',
    messagingSenderId: '285154808193',
    projectId: 'taxiapp-4e7c3',
    authDomain: 'taxiapp-4e7c3.firebaseapp.com',
    storageBucket: 'taxiapp-4e7c3.appspot.com',
    measurementId: 'G-2P44QHHXFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDciV6jLW1gqBeHsGzUOQvlMjjwvaKEKoY',
    appId: '1:285154808193:android:921f13f337d52c33cb5880',
    messagingSenderId: '285154808193',
    projectId: 'taxiapp-4e7c3',
    storageBucket: 'taxiapp-4e7c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd53Y9GUjBLeIWbxXN5BZVAPwTfk6InyU',
    appId: '1:285154808193:ios:7863f4e0794ebadfcb5880',
    messagingSenderId: '285154808193',
    projectId: 'taxiapp-4e7c3',
    storageBucket: 'taxiapp-4e7c3.appspot.com',
    iosBundleId: 'com.example.taxiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd53Y9GUjBLeIWbxXN5BZVAPwTfk6InyU',
    appId: '1:285154808193:ios:acda49a5195a125dcb5880',
    messagingSenderId: '285154808193',
    projectId: 'taxiapp-4e7c3',
    storageBucket: 'taxiapp-4e7c3.appspot.com',
    iosBundleId: 'com.example.taxiApp.RunnerTests',
  );
}
